### PR TITLE
Fix in table constraint incremental update

### LINKED ISSUE #144: General tree test eternity
The general tree test fails on the eternity 6x5 problem.

### PR DESCRIPTION
**Pull request by Wikunia**
fix #144

### CODE REVIEW

File: test/eternity.jl [hunk 1]
```diff
@@ -35,7 +35,7 @@ end
 
     ncolors = maximum(puzzle[:,2:end])
 
-    m = Model(CSJuMPTestSolver())
```
Comment (Wikunia) [inline test/eternity.jl:38]: the semantic of the `CSJuMPTestSolver()` doesn't fit. change to e.g. `CSJuMPTestOptimizer()` :)

File: test/eternity.jl [hunk 2]
```diff
@@ -35,7 +35,7 @@ end
...
+    m = Model(optimizer_with_attributes(CS.Optimizer, "keep_logs"=>true))
```
Comment (Wikunia) [inline test/eternity.jl:38]: Use `"logging" => []`

**Comment by Wikunia** [comment]
There seems to be another bug with the table constraint...
Using reset update every time doesn't solve the issue as well. 
Will check tmr :confused:
